{
 "title": "API Requests Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "API Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{pod=~\"api-deployment-.*\", container=\"api\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Payment Pods Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(prober_probe_total{pod!~\"payments-primary-.*\", container=\"payments\", result=\"successful\", probe_type=\"Liveness\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Downstream error count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(envoy_listener_http_downstream_rq_xx{local_cluster=\"ingress-gateway\", envoy_listener_address=\"0.0.0.0_18080\", envoy_response_code_class=\"5\"}[$__rate_interval]),1))"
    }
   ]
  },
  {
   "title": "Web Downstream Response",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_http_downstream_rq_xx{local_cluster=\"ingress-gateway\", envoy_listener_address=\"0.0.0.0_18080\"}[$__rate_interval])) by (envoy_response_code_class)",
     "legendFormat": "Response Code {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Retries per Second",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_retry_upstream_rq{consul_destination_service=\"payments\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Payments Request per Second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{pod!~\"payments-primary.*\", namespace=\"default\", envoy_cluster_name=\"local_app\", pod=~\"payments.*\"}[$__rate_interval]))",
     "legendFormat": "Canary - {{envoy_response_code}}"
    },
    {
     "expr": "sum by (envoy_response_code) (rate(envoy_cluster_upstream_rq{pod=~\"payments-primary.*\", namespace=\"default\", envoy_cluster_name=\"local_app\", pod=~\"payments.*\"}[$__rate_interval]))",
     "legendFormat": "Primary - {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "SMI Controller Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{app=\"smi-controller\"} |= \"TrafficSplit\""
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{app=\"api\"}"
    }
   ]
  },
  {
   "title": "Payment Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{app=~\"payment.*\"}"
    }
   ]
  }
 ]
}