---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels: # configure prom scraping for this service, this will be picked up by the default-applications ServiceMonitor
    app: metrics
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP # main port
      port: 8080
      targetPort: 8080
    - name: metrics # prom scraping port
      protocol: TCP
      port: 20200
      targetPort: 20200

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api_v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        group: api
        metrics: enabled
        app: api
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        consul.hashicorp.com/transparent-proxy-overwrite-probes: 'true'
        consul.hashicorp.com/connect-service: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.22.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: "NAME"
              value: "API"
            - name: "LISTEN_ADDR"
              value: "127.0.0.1:8080"
            - name: "HTTP_CLIENT_KEEP_ALIVES"
              value: "false"
            - name: "UPSTREAM_URIS"
              value: "http://payments.default.svc:8080"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TRACING_ZIPKIN"
              value: "http://tempo.monitoring.svc:9411"
            - name: "ERROR_RATE"
              value: "0.0"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3